// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/quiz.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Difficulty    *string                `protobuf:"bytes,2,opt,name=difficulty,proto3,oneof" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomQuestionRequest) Reset() {
	*x = GetRandomQuestionRequest{}
	mi := &file_proto_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomQuestionRequest) ProtoMessage() {}

func (x *GetRandomQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetRandomQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomQuestionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRandomQuestionRequest) GetDifficulty() string {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return ""
}

type GetQuestionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionByIdRequest) Reset() {
	*x = GetQuestionByIdRequest{}
	mi := &file_proto_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionByIdRequest) ProtoMessage() {}

func (x *GetQuestionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuestionByIdRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type QuizQuestion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoUrl       string                 `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbnailEmoji string                 `protobuf:"bytes,3,opt,name=thumbnail_emoji,json=thumbnailEmoji,proto3" json:"thumbnail_emoji,omitempty"`
	Options        []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	CorrectIndex   int32                  `protobuf:"varint,5,opt,name=correct_index,json=correctIndex,proto3" json:"correct_index,omitempty"`
	Explanation    string                 `protobuf:"bytes,6,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Difficulty     string                 `protobuf:"bytes,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuizQuestion) Reset() {
	*x = QuizQuestion{}
	mi := &file_proto_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizQuestion) ProtoMessage() {}

func (x *QuizQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizQuestion.ProtoReflect.Descriptor instead.
func (*QuizQuestion) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *QuizQuestion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizQuestion) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *QuizQuestion) GetThumbnailEmoji() string {
	if x != nil {
		return x.ThumbnailEmoji
	}
	return ""
}

func (x *QuizQuestion) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuizQuestion) GetCorrectIndex() int32 {
	if x != nil {
		return x.CorrectIndex
	}
	return 0
}

func (x *QuizQuestion) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *QuizQuestion) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type SubmitAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SelectedIndex int32                  `protobuf:"varint,3,opt,name=selected_index,json=selectedIndex,proto3" json:"selected_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_proto_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetSelectedIndex() int32 {
	if x != nil {
		return x.SelectedIndex
	}
	return 0
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correct       bool                   `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	XpEarned      int32                  `protobuf:"varint,2,opt,name=xp_earned,json=xpEarned,proto3" json:"xp_earned,omitempty"`
	CoinsEarned   int32                  `protobuf:"varint,3,opt,name=coins_earned,json=coinsEarned,proto3" json:"coins_earned,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	StreakCount   int32                  `protobuf:"varint,5,opt,name=streak_count,json=streakCount,proto3" json:"streak_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_proto_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitAnswerResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *SubmitAnswerResponse) GetXpEarned() int32 {
	if x != nil {
		return x.XpEarned
	}
	return 0
}

func (x *SubmitAnswerResponse) GetCoinsEarned() int32 {
	if x != nil {
		return x.CoinsEarned
	}
	return 0
}

func (x *SubmitAnswerResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SubmitAnswerResponse) GetStreakCount() int32 {
	if x != nil {
		return x.StreakCount
	}
	return 0
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_proto_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QuizStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAnswered int32                  `protobuf:"varint,1,opt,name=total_answered,json=totalAnswered,proto3" json:"total_answered,omitempty"`
	CorrectRate   float64                `protobuf:"fixed64,2,opt,name=correct_rate,json=correctRate,proto3" json:"correct_rate,omitempty"`
	CurrentStreak int32                  `protobuf:"varint,3,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	BestStreak    int32                  `protobuf:"varint,4,opt,name=best_streak,json=bestStreak,proto3" json:"best_streak,omitempty"`
	Lives         int32                  `protobuf:"varint,5,opt,name=lives,proto3" json:"lives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizStats) Reset() {
	*x = QuizStats{}
	mi := &file_proto_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizStats) ProtoMessage() {}

func (x *QuizStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizStats.ProtoReflect.Descriptor instead.
func (*QuizStats) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *QuizStats) GetTotalAnswered() int32 {
	if x != nil {
		return x.TotalAnswered
	}
	return 0
}

func (x *QuizStats) GetCorrectRate() float64 {
	if x != nil {
		return x.CorrectRate
	}
	return 0
}

func (x *QuizStats) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *QuizStats) GetBestStreak() int32 {
	if x != nil {
		return x.BestStreak
	}
	return 0
}

func (x *QuizStats) GetLives() int32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

var File_proto_quiz_proto protoreflect.FileDescriptor

const file_proto_quiz_proto_rawDesc = "" +
	"\n" +
	"\x10proto/quiz.proto\x12\x04quiz\"g\n" +
	"\x18GetRandomQuestionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\tH\x00R\n" +
	"difficulty\x88\x01\x01B\r\n" +
	"\v_difficulty\"9\n" +
	"\x16GetQuestionByIdRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"\xe5\x01\n" +
	"\fQuizQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\x12'\n" +
	"\x0fthumbnail_emoji\x18\x03 \x01(\tR\x0ethumbnailEmoji\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12#\n" +
	"\rcorrect_index\x18\x05 \x01(\x05R\fcorrectIndex\x12 \n" +
	"\vexplanation\x18\x06 \x01(\tR\vexplanation\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\tR\n" +
	"difficulty\"v\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12%\n" +
	"\x0eselected_index\x18\x03 \x01(\x05R\rselectedIndex\"\xb5\x01\n" +
	"\x14SubmitAnswerResponse\x12\x18\n" +
	"\acorrect\x18\x01 \x01(\bR\acorrect\x12\x1b\n" +
	"\txp_earned\x18\x02 \x01(\x05R\bxpEarned\x12!\n" +
	"\fcoins_earned\x18\x03 \x01(\x05R\vcoinsEarned\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12!\n" +
	"\fstreak_count\x18\x05 \x01(\x05R\vstreakCount\".\n" +
	"\x13GetUserStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb3\x01\n" +
	"\tQuizStats\x12%\n" +
	"\x0etotal_answered\x18\x01 \x01(\x05R\rtotalAnswered\x12!\n" +
	"\fcorrect_rate\x18\x02 \x01(\x01R\vcorrectRate\x12%\n" +
	"\x0ecurrent_streak\x18\x03 \x01(\x05R\rcurrentStreak\x12\x1f\n" +
	"\vbest_streak\x18\x04 \x01(\x05R\n" +
	"bestStreak\x12\x14\n" +
	"\x05lives\x18\x05 \x01(\x05R\x05lives2\x9e\x02\n" +
	"\vQuizService\x12G\n" +
	"\x11GetRandomQuestion\x12\x1e.quiz.GetRandomQuestionRequest\x1a\x12.quiz.QuizQuestion\x12E\n" +
	"\fSubmitAnswer\x12\x19.quiz.SubmitAnswerRequest\x1a\x1a.quiz.SubmitAnswerResponse\x12:\n" +
	"\fGetUserStats\x12\x19.quiz.GetUserStatsRequest\x1a\x0f.quiz.QuizStats\x12C\n" +
	"\x0fGetQuestionById\x12\x1c.quiz.GetQuestionByIdRequest\x1a\x12.quiz.QuizQuestionB.Z,github.com/pawfiler/backend/services/quiz/pbb\x06proto3"

var (
	file_proto_quiz_proto_rawDescOnce sync.Once
	file_proto_quiz_proto_rawDescData []byte
)

func file_proto_quiz_proto_rawDescGZIP() []byte {
	file_proto_quiz_proto_rawDescOnce.Do(func() {
		file_proto_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)))
	})
	return file_proto_quiz_proto_rawDescData
}

var file_proto_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_quiz_proto_goTypes = []any{
	(*GetRandomQuestionRequest)(nil), // 0: quiz.GetRandomQuestionRequest
	(*GetQuestionByIdRequest)(nil),   // 1: quiz.GetQuestionByIdRequest
	(*QuizQuestion)(nil),             // 2: quiz.QuizQuestion
	(*SubmitAnswerRequest)(nil),      // 3: quiz.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil),     // 4: quiz.SubmitAnswerResponse
	(*GetUserStatsRequest)(nil),      // 5: quiz.GetUserStatsRequest
	(*QuizStats)(nil),                // 6: quiz.QuizStats
}
var file_proto_quiz_proto_depIdxs = []int32{
	0, // 0: quiz.QuizService.GetRandomQuestion:input_type -> quiz.GetRandomQuestionRequest
	3, // 1: quiz.QuizService.SubmitAnswer:input_type -> quiz.SubmitAnswerRequest
	5, // 2: quiz.QuizService.GetUserStats:input_type -> quiz.GetUserStatsRequest
	1, // 3: quiz.QuizService.GetQuestionById:input_type -> quiz.GetQuestionByIdRequest
	2, // 4: quiz.QuizService.GetRandomQuestion:output_type -> quiz.QuizQuestion
	4, // 5: quiz.QuizService.SubmitAnswer:output_type -> quiz.SubmitAnswerResponse
	6, // 6: quiz.QuizService.GetUserStats:output_type -> quiz.QuizStats
	2, // 7: quiz.QuizService.GetQuestionById:output_type -> quiz.QuizQuestion
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_quiz_proto_init() }
func file_proto_quiz_proto_init() {
	if File_proto_quiz_proto != nil {
		return
	}
	file_proto_quiz_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_quiz_proto_goTypes,
		DependencyIndexes: file_proto_quiz_proto_depIdxs,
		MessageInfos:      file_proto_quiz_proto_msgTypes,
	}.Build()
	File_proto_quiz_proto = out.File
	file_proto_quiz_proto_goTypes = nil
	file_proto_quiz_proto_depIdxs = nil
}
