#!/bin/bash

echo "=== Pawfiler Services Manual Test Guide ==="
echo ""

echo "📋 방법 1: Docker 컨테이너 내부에서 직접 확인"
echo "----------------------------------------"
echo ""
echo "1. Auth Service 테스트:"
echo "   docker exec -it pawfiler-auth /bin/sh"
echo "   # 컨테이너 내부에서 프로세스 확인"
echo "   ps aux | grep auth-service"
echo ""

echo "2. Quiz Service 테스트:"
echo "   docker exec -it pawfiler-quiz /bin/sh"
echo "   ps aux | grep quiz-service"
echo ""

echo "3. Community Service 테스트:"
echo "   docker exec -it pawfiler-community /bin/sh"
echo "   ps aux | grep community-service"
echo ""

echo "4. Payment Service 테스트:"
echo "   docker exec -it pawfiler-payment /bin/sh"
echo "   ps aux | grep payment-service"
echo ""

echo "5. Dashboard BFF 테스트:"
echo "   docker exec -it pawfiler-dashboard-bff /bin/sh"
echo "   ps aux | grep dashboard-bff"
echo ""

echo "📋 방법 2: 포트 연결 확인"
echo "----------------------------------------"
echo ""
echo "각 서비스 포트가 열려있는지 확인:"
echo ""

for port in 50051 50052 50053 50055 50056; do
    if nc -z localhost $port 2>/dev/null; then
        echo "✅ Port $port is open"
    else
        echo "❌ Port $port is closed"
    fi
done

echo ""
echo "📋 방법 3: 실시간 로그 확인"
echo "----------------------------------------"
echo ""
echo "Auth Service 로그:"
echo "   docker logs -f pawfiler-auth"
echo ""
echo "Quiz Service 로그:"
echo "   docker logs -f pawfiler-quiz"
echo ""
echo "Community Service 로그:"
echo "   docker logs -f pawfiler-community"
echo ""
echo "Payment Service 로그:"
echo "   docker logs -f pawfiler-payment"
echo ""
echo "Dashboard BFF 로그:"
echo "   docker logs -f pawfiler-dashboard-bff"
echo ""

echo "📋 방법 4: grpcurl 설치 및 사용 (권장)"
echo "----------------------------------------"
echo ""
echo "grpcurl 설치:"
echo "   # Linux"
echo "   wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.9/grpcurl_1.8.9_linux_x86_64.tar.gz"
echo "   tar -xvf grpcurl_1.8.9_linux_x86_64.tar.gz"
echo "   sudo mv grpcurl /usr/local/bin/"
echo ""
echo "   # Windows (PowerShell)"
echo "   choco install grpcurl"
echo ""
echo "서비스 테스트 (reflection 활성화 필요):"
echo "   grpcurl -plaintext localhost:50051 list"
echo "   grpcurl -plaintext localhost:50052 list"
echo ""

echo "📋 방법 5: 데이터베이스 확인"
echo "----------------------------------------"
echo ""
echo "PostgreSQL 접속:"
echo "   docker exec -it pawfiler-postgres psql -U pawfiler -d pawfiler"
echo ""
echo "테이블 확인:"
echo "   \\dt"
echo ""

echo "📋 방법 6: Kafka 확인"
echo "----------------------------------------"
echo ""
echo "Kafka 토픽 목록:"
echo "   docker exec pawfiler-kafka kafka-topics --list --bootstrap-server localhost:9092"
echo ""

echo "=== 현재 실행 중인 서비스 상태 ==="
docker ps --filter "name=pawfiler" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
